<?php

namespace App\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BaseController extends AbstractController
{
    protected $errors_list;

    public function __construct()
    {
        $errors_list = array();
    }
    
    /**
     * @return string
     */
    protected function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
    
    protected  function copyImageFileTo($newsFile,$destinationDir, $fileName)
    {
        if(is_dir($destinationDir))
        {
            $newsFile->move($destinationDir,$fileName);
            if (file_exists($destinationDir. DIRECTORY_SEPARATOR .$fileName)) 
            {
                return true;
            }
        }
        return false;
    }
}
